### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by bichpham** [oxesoft/rpi-midi-ble#2]
First of all, thanks for your great work! I was able to compile the code in RPi3 but not sure how to use it. I have 2 questions below:

1. What command do I need to run to make ble app(garage band) recognize the RPi3? I was able to run ./configure --enable-midi and was able to see my midi keyboard in the RPi3 using aseqdump -l. I was able to pair (bluetooth classic) the RPi3 using bluetoothctl as well but not sure what to do for iOS to recognize the RPi3 as midi BLE device.

2. Does btmidi-server run automatically when I run ./configure --enable-midi or do I have to start it somehow.

I'm very new to bluez/linux so thanks in advance for your help!

**Comment by oxesoft** [comment]
Hi. You need to run both "./tools/btmidi-server" and "./alsa-seq-autoconnect" manually (or add it to some init script). The device sould be shown in Gareband > Song Settings > Advanced > Bluetooth MIDI Devices. It has nothing to do with the bluetooth classic in the RPI3.

**Comment by bichpham** [comment]
Thanks! Looks like I did not compile it correctly. I ran make && make install in the cloned bluez directory but it did not create .o file for btmidi-server. What command do I need to use to create an executable for that? I tried gcc command and also changing the environment path with no luck. It said missing lib/bluethooth.h

Also I could not run 'make' in the alsa-seq-autoconnect folder eventhough there is a Makefile in there already. It said "make: *** No targets specified and no makefile found.  Stop." Any idea how to fix this? I was able to run the make command in this same folder in XUbuntu without any issues. It just wont work in the RPi3 for some reason.

**Comment by oxesoft** [comment]
"./configure --enable-midi" enables the "btmidi-server" by "make". You don't need to do "make install" once we only need the "tools/btmidi-server" executable. To compile the "alsa-seq-autoconnect" you need to change to that dir first ("cd rpi-midi-ble/alsa-seq-autoconnect/") and then "make".

**Comment by bichpham** [comment]
Thanks a lot! I finally got some sound from the keyboard over BLE. I had to restart the RPi couple times because I corrupted it somehow but it works now.
