### ISSUE TITLE
How to run when Raspberry boot

### ISSUE THREAD

**Issue by bichpham** [oxesoft/rpi-midi-ble#3]
How do I run both the btmidi-server and alsa-seq-autoconnect automatically when the raspberry pi starts? I have a bash script that will run both of them fine manually but it won't run if I put it in rc.local. Any better way to do it?

**Comment by oxesoft** [comment]
I did the same but I had put a "sleep 10" before

**Comment by bichpham** [comment]
Thanks! My raspbian image was corrupted somehow. I had to get a brand new image for it to work.
