### ISSUE TITLE
Raspberry Pi GPIO Midi

### ISSUE THREAD

**Issue by bichpham** [oxesoft/rpi-midi-ble#4]
Is there a way I can manually send note and velocity using any of the routine in Btmidi-server or alsa-seq-autoconnect? I'm trying to connect couple pushbuttons to the gpio pins and have them play some notes in garageband.

**Comment by oxesoft** [comment]
You need to create a alsa-seq port and send the MIDI event bytes thru it, as a standalone app. Take a look at the alsa repo.
