### ISSUE TITLE
How to make Rpi ble show meaningful name in iOS

### ISSUE THREAD

**Issue by bichpham** [oxesoft/rpi-midi-ble#5]
Hi,

Thank you so much for the cool code. Currently whenever I run the code, the device show up in iOS garage band as "A78AD39D-1053-xxxxxxx-xxxxxxx-xxxxxx". Is there any way to change that name to something more meaningful such as "Raspberry Pi BLE" or something?....

**Comment by oxesoft** [comment]
The btmidi-server sets the name as "BLE-MIDI Device". Maybe the iOS is not querying the name before to show it in the device list.

**Comment by bichpham** [comment]
Thanks. I figured it out. I moved my Microsd to another raspberry pi and the old name was in the list. iOs did not know which “BLE MIDi Device” is which so it was probably displaying the physical address. Clearing the BLE list fixed the problem
